### ISSUE TITLE
Latency feedback in Data tab

### ISSUE THREAD

**Issue by sergiimk** [kamu-data/kamu-web-ui#198]
When using a remote platform (e.g. https://platform.demo.kamu.dev/) and larger datasets the Data tab does not react well to increased latency.

When I first switch to Data tab I see empty "Query" section, which is very confusing, and only after a few seconds the query SQL will appear along with a refresh of the "Result" table.

Let's test "Data" tab with simulated latency, ensure SQL code appears without blocking on results, and add user feedback where necessary.

**Comment by zaychenko-sergei** [comment]
According to Dmitriy's research: the delay is unrelated to data loads, it's a result of long Monaco initialization, and happens only first time.
