### ISSUE TITLE
Replace spinner with less invasive progress bar

### ISSUE THREAD

**Issue by sergiimk** [kamu-data/kamu-web-ui#221]
Currently when we are waiting for API server's response we show a big spinner in the center of the screen.

Because it's so "in-your-face" and distracting we later added a short delay not to show the spinner unless request is taking more than N milliseconds, but this also IMO reduced the feeling of responsiveness.

This proposal is to change the style of this feedback from spinner at the center to a progress bar at the top of the window (just like in GitHub).

Logic:
* This progress bar will be displayed immediately without any delay - making UI more "responsive"
* Since we don't really know how long some request will take - the actual progress should just asymptotically approach 90% until we receive a response - the movement of the progress itself will give user a feeling that things are progressing

**Comment by zaychenko-sergei** [comment]
This feedback is very subjective. I like the spinner we have.
