### ISSUE TITLE
Support "open in new tab/window" shortcuts

### ISSUE THREAD

**Issue by sergiimk** [kamu-data/kamu-web-ui#294]
When CTRL+Clicking on links (like dataset names in the search view) or on tabs in dataset view it is expected that destination URL will be opened in a new browser tab.

Similarly when I right-click on a tab e.g. in GitHub I see options like "Open link in new window", but I don't get such options in our UI.

**Comment by sergiimk** [comment]
Re-opening as this seems to work only for dataset view tabs (although there is a glitch when doing it).

Open in new tab/window doesn't work for any links:
- dataset names
- account names
- history blocks
- lineage nodes
- settings vertical tabs / sub-menues

**Comment by dmitriy-borzenko** [comment]
Unfortunately, it is impossible to make graph nodes links, since they are svg images.
