### ISSUE TITLE
Style: Use multi-line fields for ETH filter & signature

### ISSUE THREAD

**Issue by sergiimk** [kamu-data/kamu-web-ui#341]
In [this dataset](https://platform.demo.kamu.dev/kamu/net.rocketpool.reth.tokens-burned/block/f1620b2c1eacc8c0eaa7eea37c8502dc71a81c9ae2fa1175951f80b562d1a96b5274a) `EthereumLogs` source block `Filter` and `Signature` fields are hard to read:
![image](https://github.com/kamu-data/kamu-web-ui/assets/204914/c0f4796a-db31-47c9-87f9-dac824d1bfdc)

They look much cleaner in YAML where they appear as multi-line:
![image](https://github.com/kamu-data/kamu-web-ui/assets/204914/84a57299-d327-40c7-924f-e2a99ad75964)

I suggest to use the "code block" widget (same as we use for YAML and SQL) to display them so that line breaks are preserved.

**Comment by dmitriy-borzenko** [comment]
Result:

![image](https://github.com/kamu-data/kamu-web-ui/assets/51016717/2b13d77b-6229-40eb-b8e7-7f25a42e6c56)
