### ISSUE TITLE
Add Information action should reflect changes on save

### ISSUE THREAD

**Issue by sergiimk** [kamu-data/kamu-web-ui#348]
### Steps to reproduce
1. Create new dataset
1. Click `Add Information` action
  ![image](https://github.com/user-attachments/assets/08695922-5d51-492a-b1e1-1bac77bddd29)
1. Fill in some details
  ![image](https://github.com/user-attachments/assets/efda64bf-fdfb-4e49-b1ee-4d6a0d46df11)
1. Hit `Save`
1. Observe UI unchanged
  ![image](https://github.com/user-attachments/assets/31a82785-bd08-43de-822d-853c7c5a81a2)

UI is updated only after refreshing the page:
![image](https://github.com/user-attachments/assets/8bd0b770-abbc-4bfb-97a8-70be70722f61) 

### Expectation
After hitting `Save` the UI is refreshed to include the changes made.

**Comment by dmitriy-borzenko** [comment]
The same, the latest version 0.23.0 does not have this problem. You need to update the deployment to the latest version. This cache problem appeared with the introduction of many accounts. Now she's gone
