### ISSUE TITLE
Deleted dataset stays in app cache

### ISSUE THREAD

**Issue by sergiimk** [kamu-data/kamu-web-ui#355]
## Steps to reproduce
- Create a dataset
- Open `Your Datasets` page
- Click on the new dataset
- Go to Setting and delete the dataset
- Go to `Your Datasets` page again
- Observe that the deleted dataset is still present
- Dataset is gone after refreshing the page

## Expectations
Dataset does not appear in any lists after being deleted

**Comment by dmitriy-borzenko** [comment]
The latest version 0.23.0 does not have this problem. You need to update the deployment to the latest version.

**Comment by sergiimk** [comment]
Ok, thanks for checking. Closing.
