### ISSUE TITLE
Reset + flatten metadata option is missing for derivative datasets

### ISSUE THREAD

**Issue by sergiimk** [kamu-data/kamu-web-ui#405]
Root dataset provides options to reset to Seed or "flatten":
![image](https://github.com/user-attachments/assets/164446ad-ba90-4f80-b5fb-d997c7f3ce39)

Derivative dataset shows only reset to Seed:
![image](https://github.com/user-attachments/assets/b606a2e0-8cc6-4e71-a23a-0ecf886e9a87)

Ability to flattening metadata is as important for derivative datasets as for root. This allows to thrown derivative data away and start processing from scratch. Resetting to Seed means you lose the defined queries and have to re-create the SetTransfrom block.

**Comment by zaychenko-sergei** [comment]
Obviously, it's explicitly disabled, as backend does not allow such a combination.
Requirements clarification discussion is necessary.
