### ISSUE TITLE
Detect when dataset cache is stale

### ISSUE THREAD

**Issue by sergiimk** [kamu-data/kamu-web-ui#406]
Currently when triggering flows via `Update now` button, or resetting dataset via settings when you go back to "Overview" tab you still see the old state and need to manually Refresh.

It would be a significant UX improvement if we could detect that our cache is stale and refresh it automatically.

Before we have push notifications a simple ways to achieve this could be:
- save the last dataset block hash
- when returning to "Overview" tab do a minimal request to see if latest block hash changed
- trigger a full refresh of the cache if it did

**Comment by zaychenko-sergei** [comment]
We simply have to reset the parts of the dataset cache that are affected with the operation, like we do in other places.
