### ISSUE TITLE
Variables and secrets: friendlier display, in case of non-activated API

### ISSUE THREAD

**Issue by s373r** [kamu-data/kamu-web-ui#448]
### Describe the bug

On the backend side, the environment variables API may be inactivated. 

### Current Behavior

In this case, we will show a toast with an error and allow the tab to be displayed to change env vars:

![image(1)](https://github.com/user-attachments/assets/907d758a-720b-4f3a-a769-683d0d2171f9)

### Expected Behavior

As a suggestion: in case the API is unavailable, turn off (disable) the "Variables and secrets" menu:

![image_2024-09-30_14-02-45](https://github.com/user-attachments/assets/9159746b-2135-4429-a371-b7a3d41ff3da)

**Comment by zaychenko-sergei** [comment]
Part of larger #397

**Comment by s373r** [comment]
@zaychenko-sergei , seems to be more of a problem on the `kamu-cli` side, if we run it as an API server.

In the case of running `kamu ui`, we provide `/assets/runtime-config.json`, while in the case of `kamu system api-server`, we do not

**Comment by zaychenko-sergei** [comment]
> @zaychenko-sergei , seems to be more of a problem on the `kamu-cli` side, if we run it as an API server.
> 
> In the case of running `kamu ui`, we provide `/assets/runtime-config.json`, while in the case of `kamu system api-server`, we do not

Before the default configuration was satisfying.
