### ISSUE TITLE
Anonymous / non-admin users unable to view Query Explainer

### ISSUE THREAD

**Issue by sergiimk** [kamu-data/kamu-web-ui#462]
Steps to reproduce:
- Open https://platform.demo.kamu.dev
- Log in as admin user
- Open data tab and run query `select 1`
- Click "Verify query result" button
- Copy the URL
- Logout
- Paste the old explainer URL - observe redirect to home
- Login as non-admin user
- Paste the old explainer URL - observe redirect to home

Expectation:
Query explainer view should be available to all users (non admin, and anonymous) its the permissions that user has for input datasets that should determine whether user re-run certain SQL query.

Only the "Verify query result" button is visible to admins only (for demo purposes), but the route itself shouldn't be admin-only.

**Comment by dmitriy-borzenko** [comment]
Related ticket https://github.com/kamu-data/kamu-web-ui/issues/464
